# Symmetric Matrix

A symmetric matrix is a square matrix that is equal to its own transpose. This means the matrix remains unchanged when reflected across its main diagonal. Mathematically, for a matrix A to be symmetric, the element in row i and column j (aij) must be equal to the element in row j and column i (aji) for all i and j. 

[Symmetric and Skew Symmetric Matrices](https://www.geeksforgeeks.org/maths/what-is-symmetric-matrix-and-skew-symmetric-matrix/)

For example, let us consider a square matrix 

## Numpy

In [ ]:
import numpy as np

In [ ]:
X_sym = np.array([[3,4],[4,5]])
X_sym

In [ ]:
X_sym.T

## Torch

In [ ]:
import torch

In [ ]:
X_pt = torch.tensor([[3,4],[4,5]])
X_pt

In [ ]:
X_pt.T

## Tensorflow

In [ ]:
import tensorflow as tf

In [ ]:
X_tf = tf.Variable([[3,4],[4,5]])
X_tf

In [ ]:
tf.transpose(X_tf)

# Identity Matrices

## Numpy

In [ ]:
import numpy as np

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Torch

In [14]:
import torch

In [15]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## Tensorflow

In [ ]:
import tensorflow as tf

In [16]:
tf.eye(num_rows=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>