In [ ]:
import numpy as np
import torch
import tensorflow as tf

# Eigenvectors and Eigenvalues

In [ ]:
A = np.array([[-1,  4], [ 2, -2]])
lambdas, V = np.linalg.eig(A)
print("lambdas: ",lambdas)
print("V: ", V)


In [ ]:
np.dot(A,V)

In [ ]:
np.matmul(lambdas, V)

In [ ]:
np.dot(A,V[:,0])

In [ ]:
np.dot(A,V[:,1])

In [ ]:
np.dot(A,V[:,0]) == np.dot(lambdas[0], V[:,0])

In [ ]:
np.dot(A,V[:,1]) == np.dot(lambdas[1], V[:,1])

# Matrix Determinants

## 2 x 2

In [ ]:
x = np.array([[4, 2], [-5, -3]])
print(x)
print(np.linalg.det(x))

In [ ]:
x = torch.tensor([[4, 2], [-5, -3.]])
print(x)
print(torch.linalg.det(x))

In [ ]:
x = tf.Variable([[4, 2], [-5, -3.]])
print(x)
print(tf.linalg.det(x))

## multiple

In [ ]:
x = np.array([[1, 2, 4], [3, 5, 2], [1, 0, 3]])
print(x)
print(np.linalg.det(x))

In [ ]:
x = torch.tensor([[1, 2, 4], [3, 5, 2], [1, 0, 3.]])
print(x)
print(torch.linalg.det(x))

In [ ]:
x = tf.Variable([[1, 2, 4], [3, 5, 2], [1, 0, 3.]])
print(x)
print(tf.linalg.det(x))

In [ ]:
x = np.array([[2, 1, -3], [4, -5, 2], [0, -1, 3]])
print(x)
print(np.linalg.det(x))

# Copilot examples

To calculate the **determinant of a 3×3 matrix**, we use a method called **cofactor expansion**. Here's how to do it step by step for your matrix:
$$
A = \begin{bmatrix}
2 & 1 & -3 \\
4 & -5 & 2 \\
0 & -1 & 3
\end{bmatrix}
$$
---

### 🧮 Step-by-Step Determinant Calculation

We’ll expand along the **first row** (you can choose any row or column, but the first row is often easiest):

$$
\text{det}(A) = a_{11} \cdot C_{11} - a_{12} \cdot C_{12} + a_{13} \cdot C_{13}
$$

Where:
- \( a_{ij} \) is the element in row *i*, column *j*
- \( C_{ij} \) is the determinant of the 2×2 minor matrix formed by removing row *i* and column *j*

---

#### 🔹 Step 1: Expand the determinant

$$
\text{det}(A) = 2 \cdot \begin{vmatrix} -5 & 2 \\ -1 & 3 \end{vmatrix}
- 1 \cdot \begin{vmatrix} 4 & 2 \\ 0 & 3 \end{vmatrix}
+ (-3) \cdot \begin{vmatrix} 4 & -5 \\ 0 & -1 \end{vmatrix}
$$

---

#### 🔹 Step 2: Calculate each 2×2 determinant
$$
- \begin{vmatrix} -5 & 2 \\ -1 & 3 \end{vmatrix} = (-5)(3) - (2)(-1) = -15 + 2 = -13
$$
$$
- \begin{vmatrix} 4 & 2 \\ 0 & 3 \end{vmatrix} = (4)(3) - (2)(0) = 12 - 0 = 12
$$
$$
- \begin{vmatrix} 4 & -5 \\ 0 & -1 \end{vmatrix} = (4)(-1) - (-5)(0) = -4 - 0 = -4
$$
---

#### 🔹 Step 3: Plug values back in

$$
\text{det}(A) = 2(-13) - 1(12) + (-3)(-4)
= -26 - 12 + 12 = -26
$$

---

### ✅ Final Answer

$$
\boxed{\text{det}(A) = -26}
$$

diagonal method
Yes, Samuel! For a **3×3 matrix**, there's a shortcut called the **diagonal method** or **Sarrus' Rule** — it's a neat trick that works only for 3×3 matrices. Here's how it works for your matrix:

$$
A = \begin{bmatrix}
2 & 1 & -3 \\
4 & -5 & 2 \\
0 & -1 & 3
\end{bmatrix}
$$

---

### 🔷 Step-by-Step: Diagonal Method (Sarrus' Rule)

#### 🔹 Step 1: Write the matrix and repeat the first two columns

Extend the matrix by writing the first two columns again to the right:

$$
\begin{array}{ccc|cc}
2 & 1 & -3 & 2 & 1 \\
4 & -5 & 2 & 4 & -5 \\
0 & -1 & 3 & 0 & -1 \\
\end{array}
$$

---

#### 🔹 Step 2: Add the products of the **three downward diagonals**
$$
D_1 = 2 \cdot (-5) \cdot 3 = -30 \\
D_2 = 1 \cdot 2 \cdot 0 = 0 \\
D_3 = -3 \cdot 4 \cdot (-1) = 12
$$
Sum of downward diagonals:
$$
S_1 = -30 + 0 + 12 = -18
$$
---

#### 🔹 Step 3: Subtract the products of the **three upward diagonals**

$$
U_1 = 0 \cdot (-5) \cdot (-3) = 0 \\
U_2 = -1 \cdot 2 \cdot 2 = -4 \\
U_3 = 3 \cdot 4 \cdot 1 = 12
$$
Sum of upward diagonals:  
$$
S_2 = 0 + (-4) + 12 = 8
$$
---

#### 🔹 Step 4: Final Determinant
$$
\text{det}(A) = S_1 - S_2 = -18 - 8 = -26
$$
---

### ✅ Final Answer
$$
\boxed{\text{det}(A) = -26}
$$
Same result as the cofactor method — just faster for 3×3! Want to try this method on another matrix or see how it breaks down visually?


# New Section

In [30]:
A = np.array([[2, 1], [1, 2.]])

In [31]:
lambdas, Q = np.linalg.eig(A)
print(f"lambdas:\n{lambdas}\nQ:\n {Q}")

lambdas:
[3. 1.]
Q:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [35]:
Lambda = np.diag(lambdas)
Lambda

array([[3., 0.],
       [0., 1.]])

In [36]:
np.dot(Q, np.dot(Lambda, Q.T))

array([[2., 1.],
       [1., 2.]])